spring:
  application:
    name: product
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xsp520
    url: jdbc:mysql://127.0.0.1:3306/cherry-cell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
